Check/Controllers/HousingSelectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Check.Views
{
    public class HousingSelectController : Controller
    {
        // GET: HousingSelect
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

Check/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Check.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

Check/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Check.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }
    }
}

Check/Views/HousingSelect/Confirmation.cshtml
@{
    ViewBag.Title = "Housing Confirmation";
}

<section class="HousingSelection-page">
    <form>
        <div class="d-flex flex-lg-row  flex-md-column  flex-sm-column flex-xs-column m-10 justify-content-center align-content-center">
            <div class="hSelection col bg-light justify-content-center align-content-center rounded-lg p-5">
                <h1 class="title">Housing Selection Confirmation</h1>
                <hr />

                <div class="d-flex flex-lg-row flex-md-column flex-sm-column flex-xs-column justify-content-center align-content-center">
                    <div class="col m-1 p-4">
                        <h2>Student Information</h2>
                        <hr />
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="ID Number" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" disabled>
                        </div>
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="First Name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" disabled>
                        </div>
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="Last Name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" disabled>
                        </div>
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="School Email (user@moval.edu)" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" disabled>
                        </div>
                        <div class="input-group">
                            <textarea class="form-control" placeholder="Please include any additional notes if you have any:" disabled></textarea>
                        </div>
                        <h2 class="mt-4">Housing Information</h2>
                        <hr />
                        <label class="m-2">Preferred Residence Hall:</label><br />
                        <select class="custom-select custom-select-lg" disabled>
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                    </div>
                    <div class="col m-0 p-4">
                        <h2>Roommate Preferences</h2>
                        <hr />
                        <label class="m-2">Preferred Roommate #1:</label><br />
                        <select class="custom-select custom-select-lg" disabled>
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                        <label class="m-2">Preferred Roommate #2:</label><br />
                        <select class="custom-select custom-select-lg" disabled>
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                        <label class="m-2">Preferred Roommate #3:</label><br />
                        <select class="custom-select custom-select-lg" disabled>
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                        <label class="m-2">Preferred Roommate #4:</label><br />
                        <select class="custom-select custom-select-lg" disabled>
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="p-1 mt-1 text-center"><button type="button" data-toggle="modal" data-target="#Instructions-modal" class="btn btn-primary text-center mr-4 mb-1">Submit<i class="fas text-center ml-3 fa-sign-in-alt"></i></button></div>
        <div class="p-1 mt-1 text-center"><button type="button" onclick="window.location='@Url.Action("Index", "HousingSelect")'" class="btn btn-primary text-center mr-4 mb-1">Go Back<i class="fas text-center ml-3 fa-arrow-circle-left"></i></button></div>
        
        <div class="modal hide fade in" id="Instructions-modal" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Instructions</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p class="text-justify">Have you checked your Housing information is correct?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary text-center mr-4 mb-4" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-primary text-center mr-4 mb-4" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

Check/Views/HousingSelect/Index.cshtml
@{
    ViewBag.Title = "Housing Portal";
}

<section class="HousingSelection-page">
    <form>
        <div class="d-flex flex-lg-row  flex-md-column  flex-sm-column flex-xs-column m-10 justify-content-center align-content-center">
            <div class="hSelection col bg-light justify-content-center align-content-center rounded-lg p-5">
                <h1 class="title">Housing Selection Portal</h1>
                <hr />
                <div class="d-flex flex-lg-row flex-md-column flex-sm-column flex-xs-column justify-content-center align-content-center">
                    <div class="col m-1 p-4">
                        <h2>Student Information</h2>
                        <hr />
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="ID Number" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                        </div>
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="First Name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                        </div>
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="Last Name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                        </div>
                        <div class="input-group input-group-md mb-3">
                            <input type="text" placeholder="School Email (user@moval.edu)" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                        </div>
                        <div class="input-group">
                            <textarea class="form-control" placeholder="Please include any additional notes if you have any:"></textarea>
                        </div>
                        <h2 class="mt-4">Housing Information</h2>
                        <hr />
                        <label class="m-2">Preferred Residence Hall:</label><br />
                        <select class="custom-select custom-select-lg">
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                    </div>
                    <div class="col m-0 p-4">
                        <h2>Roommate Preferences</h2>
                        <hr />
                        <label class="m-2">Preferred Roommate #1:</label><br />
                        <select class="custom-select custom-select-lg">
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                        <label class="m-2">Preferred Roommate #2:</label><br />
                        <select class="custom-select custom-select-lg">
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                        <label class="m-2">Preferred Roommate #3:</label><br />
                        <select class="custom-select custom-select-lg">
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                        <label class="m-2">Preferred Roommate #4:</label><br />
                        <select class="custom-select custom-select-lg">
                            <option>None</option>
                            <option>0</option>
                            <option>1</option>
                            <option>2</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="p-1 mt-4 text-center"><button type="button" onclick="window.location='@Url.Action("Confirmation", "HousingSelect")'" class="btn btn-primary text-center mr-4 mb-4">Continue<i class="fas text-center ml-3 fa-arrow-circle-right"></i></button></div>
    </form>

    <div class="p-1 text-center">
        <button data-toggle="modal" data-target="#Instructions-modal" class="btn btn-primary mr-4 mb-4">Instructions<i class="fas text-center ml-3 fa-angle-up"></i></button>
    </div>
    <div class="modal fade in" id="Instructions-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Instructions</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="text-justify">
                        The priority of housing, is as follows:
                        <br />
                        <br />
                        1st: Honor's Program Students<br />
                        2nd: Seniors<br />
                        3rd: Juniors<br />
                        4th: Sophomores<br />
                        5th: Freshman<br />
                        <br />
                        Please be already familiar with who you want to live with and communicate that to them prior to filling this form! Please also have several options on where you want to live as spaces fill up very quickly.
                        <br /><br />
                        If a building, apartment, room, etc is not listed that means it has already filled for the Fall 2021 semester!
                        <br /><br />
                        As always, to be eligible to select your housing you must have completed a housing contract for the 2020-2021 school year, which is available on the Missouri Valley Website.
                        <br /><br />
                        For Valley/Viking Village apartments, all occupants must have a 2.5 GPA at the time of selection.
                        <br /><br />
                        Your email address will be recorded when you submit this form.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-Exit" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</section>

Check/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
}

<section class="Login-page">
    <div class="d-flex flex-lg-row  flex-md-column  flex-sm-column flex-xs-column m-10 justify-content-center align-content-center">
        <div class="col justify-content-center align-content-center">
            <div class="p-1 text-center">
                <img class="Logo-mvc" src="~/Content/Assets/mvclogo.svg" />
            </div>
        </div>

        <div class="Layout col bg-light justify-content-center align-content-center rounded-lg p-5">
            <!--Forms for Log In -->
            <form>
                <h1 class="title">Log-in your MVC Account</h1>

                <!--New User Link-->
                <p>New User? <span class="link">@Html.ActionLink("Sign-Up", "Index", "SignUp")</span></p>
                <hr />


                <!-- Input Groups (Student ID And Password)-->
                <!--Student ID-->
                <div class="input-group input-group-md mb-3">
                    <input type="text" placeholder="Student ID" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                </div>
                <!--Password-->
                <div class="input-group input-group-md mb-3">
                    <input type="password" placeholder="Password or Temporary PIN" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                </div>
                <a class="Login-link" href="#"><p>@Html.ActionLink("Forgot password?", "Index", "SignUp")</p></a>
                <div class="g-recaptcha" data-sitekey="your_site_key"></div>
                <br />

                <!--Log In Button-->
                <div class="p-1 text-center"><button type="button" class="btn btn-primary text-center mr-4 mb-4">Log In<i class="fas text-center ml-3 fa-sign-in-alt"></i></button></div>
            </form>
            <!--Modal Button for Instructions-->
            <div class="p-1 text-center">
                <button data-toggle="modal" data-target="#Instructions-modal" class="btn btn-primary mr-4 mb-4">Instructions<i class="fas text-center ml-3 fa-angle-up"></i></button>
            </div>


            <!--Modal Information-->
            <div class="modal fade in" id="Instructions-modal" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Instructions</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="text-justify">If you have used this system before, you can log-in with your ID number and the password you have previously created for this portal. If you are a new user, please enter your MVC ID Number check the reCaptcha box/Challenge and click on [New User / Forgot Password]. The system will walk you through the new user/forgot password process afterwards.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-Exit" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Check/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="~/Content/Site.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/Responsive.css" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap" rel="stylesheet">
    <script src="~/Scripts/scrollreveal.js"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <title>@ViewBag.Title - MVC Housing Portal</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-purple">
        <div class="container text-center align-content-center justify-content-center">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse space-evenly navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <!--   <li class="nav-item">@Html.ActionLink("Home","Index", "Home")</li> -->
                </ul>

            </div>

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Missouri Valley College</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/Animations.js"></script>
</body>
</html>

Check/Views/SignUp/Index.cshtml
@{
    ViewBag.Title = "SignUp";
}
<section class="SignUp-page">
    <div class="p-1 text-center">
        <img class="w-75 shadow-lg rounded-lg" src="~/Content/Assets/MVC-Missouri-Valley-Logo-MO-Val-1000-563.png" />
    </div>
    <div class="d-flex flex-lg-row  flex-md-column  flex-sm-column flex-xs-column m-10 justify-content-center align-content-center">
     
        <div class="Layout col bg-light justify-content-center align-content-center rounded-lg p-5">

            <!--Forms for Sign In -->
            <form>
                <h1 class="title">MVC Sign Up Portal</h1>

                <!--New User Link-->
                <h4 class="link"><span>@Html.ActionLink("Go back to the Login", "Index", "Login")</span></h4>
                <hr />

                <div class="input-group input-group-md mb-3">
                    <input type="text" placeholder="Student ID" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                </div>

                <div class="input-group input-group-md mb-3">
                    <input type="text" placeholder="Student Email" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
                </div>            
                <br />
                <div class="p-1 text-center"><button type="button" class="btn btn-primary text-center mr-4 mb-4">Sign Up<i class="fas text-center ml-3 fa-sign-in-alt"></i></button></div>



            </form>
            <div class="p-1 text-center">
                <button data-toggle="modal" data-target="#Instructions-modal" class="btn btn-primary mr-4 mb-4">Instructions<i class="fas text-center ml-3 fa-angle-up"></i></button>
            </div>

            <div class="modal hide fade in" id="Instructions-modal" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Instructions</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="text-justify">Please complete the form below to set-up your account. Make sure to provide your Missouri Valley College email address if you are enrolled in class or if you are a returning student. If not, please provide the email address you used in your application for Admissions. On successful verification of your data, an email will be sent to you to complete your sign-up process.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-Exit" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>